### ISSUE TITLE
Bug: Application Crashes on Startup

### ISSUE THREAD

**Issue by larrasket** [antaz/tahrir#1]
**Description:**
When launching the application, it immediately crashes with an "Unexpected Error" message. This issue prevents users from accessing any functionality of the app.

**Steps to Reproduce:**
1. Clone the repository.
2. Navigate to the project directory.
3. Run `npm install` to install dependencies.
4. Run `npm start` to launch the application.
5. Observe the crash on startup.

**Expected Behavior:**
The application should start without errors and display the main interface.

**Actual Behavior:**
The application crashes immediately with the following error message:
```
Unexpected Error: Cannot read property 'map' of undefined
```

**Environment:**
- OS: Windows 10
- Node.js version: 14.17.0
- npm version: 6.14.13

**Additional Information:**
The error seems to be related to the initial data fetching logic. The `map` function is being called on an undefined variable in `App.js` at line 45.

**Potential Fix:**
Review the data fetching logic and ensure the variable being mapped is properly initialized. Add error handling to manage cases where the data might be undefined.

**Comment by antaz** [comment]
@larrasket congratulations on your first bad issue 🎉
